In [222]:
import pandas as pd
import numpy as np

In [223]:
df = pd.read_csv("../datasets/AMD.csv")

In [224]:
df.shape

(582, 30)

In [225]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 582 entries, 0 to 581
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   model              582 non-null    str
 1   launchDate         261 non-null    float64
 2   numCores           577 non-null    float64
 3   numThreads         522 non-null    float64
 4   baseClock          582 non-null    float64
 5   maxboostClock      501 non-null    float64
 6   allCoreBoostSpeed  14 non-null     float64
 7   L1Cache            323 non-null    float64
 8   L2Cache            516 non-null    float64
 9   L3Cache            375 non-null    float64
 10  processTech        480 non-null    float64
 11  PCIeVersion        324 non-null    float64
 12  PCIeLanes          104 non-null    float64
 13  defaultTDP         574 non-null    float64
 14  configTDP          151 non-null    str
 15  tjMax              447 non-null    float64
 16  sysMemType         510 non-null    str
 17  sysMemSpecs        484 non-null    float64
 18  memChannels        402 non-null    float64
 19  perSocketMemBW     62 non-null     float64
 20  graphicsCores      254 non-null    float64
 21  graphicsFreq       296 non-null    float64
 22  unlocked           489 non-null    str
 23  platform           582 non-null    str
 24  cpuSocket          555 non-null    str
 25  socketCount        80 non-null     str
 26  family             582 non-null    str
 27  line               582 non-null    str
 28  graphicsModel      313 non-null    str
 29  thermalSolution    47 non-null     str
dtypes: float64(19), str(11)
memory usage: 136.5 KB

In [226]:
df.isna().sum()

model                  0
launchDate           321
numCores               5
numThreads            60
baseClock              0
maxboostClock         81
allCoreBoostSpeed    568
L1Cache              259
L2Cache               66
L3Cache              207
processTech          102
PCIeVersion          258
PCIeLanes            478
defaultTDP             8
configTDP            431
tjMax                135
sysMemType            72
sysMemSpecs           98
memChannels          180
perSocketMemBW       520
graphicsCores        328
graphicsFreq         286
unlocked              93
platform               0
cpuSocket             27
socketCount          502
family                 0
line                   0
graphicsModel        269
thermalSolution      535
dtype: int64

In [227]:
df = df[df['platform'] == 'Desktop']

In [228]:
df.head()

,model,launchDate,numCores,numThreads,baseClock,maxboostClock,allCoreBoostSpeed,L1Cache,L2Cache,L3Cache,...,graphicsCores,graphicsFreq,unlocked,platform,cpuSocket,socketCount,family,line,graphicsModel,thermalSolution
18,AMD Ryzen™ 3 PRO 5350G,2021.0,4.0,8.0,4.0,4.2,NaN,NaN,2.0,8.0,...,6.0,1700.0,No,Desktop,AM4,NaN,AMD Ryzen™ PRO Processors,AMD Ryzen™ 3 PRO 5000 Series Desktop Processors,Radeon™ Graphics,NaN
19,AMD Ryzen™ 3 PRO 5350GE,2021.0,4.0,8.0,3.6,4.2,NaN,NaN,2.0,8.0,...,6.0,1700.0,No,Desktop,AM4,NaN,AMD Ryzen™ PRO Processors,AMD Ryzen™ 3 PRO 5000 Series Desktop Processors,Radeon™ Graphics,NaN
20,AMD Ryzen™ 5 PRO 5650G,2021.0,6.0,12.0,3.9,4.4,NaN,NaN,3.0,16.0,...,7.0,1900.0,No,Desktop,AM4,NaN,AMD Ryzen™ PRO Processors,AMD Ryzen™ 5 PRO 5000 Series Desktop Processors,Radeon™ Graphics,NaN
21,AMD Ryzen™ 5 PRO 5650GE,2021.0,6.0,12.0,3.4,4.4,NaN,NaN,3.0,16.0,...,7.0,1900.0,No,Desktop,AM4,NaN,AMD Ryzen™ PRO Processors,AMD Ryzen™ 5 PRO 5000 Series Desktop Processors,Radeon™ Graphics,NaN
22,AMD Ryzen™ 7 PRO 5750G,2021.0,8.0,16.0,3.8,4.6,NaN,NaN,4.0,16.0,...,8.0,2000.0,No,Desktop,AM4,NaN,AMD Ryzen™ PRO Processors,AMD Ryzen™ 7 PRO 5000 Series Desktop Processors,Radeon™ Graphics,NaN

In [229]:
df = df[['model', 'launchDate', 'numCores', 'numThreads', 'baseClock', 'maxboostClock', 'L1Cache', 'L2Cache', 'L3Cache', 'sysMemType', 'sysMemSpecs', 'cpuSocket']]

In [230]:
df = df.rename(columns={'model': 'processor', 'launchDate': 'year', 'numCores': 'cores', 'numThreads': 'threads', 'sysMemType': 'memType', 'sysMemSpecs': 'memSpecs', 'cpuSocket': 'Socket'})

In [231]:
df.info()

<class 'pandas.DataFrame'>
Index: 267 entries, 18 to 575
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   processor      267 non-null    str
 1   year           127 non-null    float64
 2   cores          264 non-null    float64
 3   threads        238 non-null    float64
 4   baseClock      267 non-null    float64
 5   maxboostClock  224 non-null    float64
 6   L1Cache        193 non-null    float64
 7   L2Cache        264 non-null    float64
 8   L3Cache        159 non-null    float64
 9   memType        234 non-null    str
 10  memSpecs       227 non-null    float64
 11  Socket         264 non-null    str
dtypes: float64(9), str(3)
memory usage: 27.1 KB

In [232]:
df.head()

,processor,year,cores,threads,baseClock,maxboostClock,L1Cache,L2Cache,L3Cache,memType,memSpecs,Socket
18,AMD Ryzen™ 3 PRO 5350G,2021.0,4.0,8.0,4.0,4.2,NaN,2.0,8.0,DDR4,3200.0,AM4
19,AMD Ryzen™ 3 PRO 5350GE,2021.0,4.0,8.0,3.6,4.2,NaN,2.0,8.0,DDR4,3200.0,AM4
20,AMD Ryzen™ 5 PRO 5650G,2021.0,6.0,12.0,3.9,4.4,NaN,3.0,16.0,DDR4,3200.0,AM4
21,AMD Ryzen™ 5 PRO 5650GE,2021.0,6.0,12.0,3.4,4.4,NaN,3.0,16.0,DDR4,3200.0,AM4
22,AMD Ryzen™ 7 PRO 5750G,2021.0,8.0,16.0,3.8,4.6,NaN,4.0,16.0,DDR4,3200.0,AM4

In [233]:
df2 = pd.read_csv("../datasets/INTEL.csv")

In [234]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 2880 entries, 0 to 2879
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product        2880 non-null   str
 1   releaseDate    2468 non-null   float64
 2   cores          2880 non-null   int64
 3   threads        943 non-null    float64
 4   maxTurboClock  1421 non-null   float64
 5   baseClock      2818 non-null   float64
 6   cache          2824 non-null   float64
 7   cacheInfo      2314 non-null   str
 8   TDP            952 non-null    float64
 9   lith           948 non-null    float64
 10  status         2880 non-null   str
 11  integratedG    1210 non-null   str
dtypes: float64(7), int64(1), str(4)
memory usage: 270.1 KB

In [235]:
df2.head()

,product,releaseDate,cores,threads,maxTurboClock,baseClock,cache,cacheInfo,TDP,lith,status,integratedG
0,Atom x6200FE,2021.0,2,NaN,NaN,1.0,1.5,NaN,NaN,NaN,Launched,NaN
1,Atom x6211E,2021.0,2,NaN,NaN,1.3,1.5,L2 Cache,NaN,NaN,Launched,Intel UHD Graphics for 10th Generation Intel C...
2,Atom x6212RE,2021.0,2,NaN,NaN,1.2,1.5,L2 Cache,NaN,NaN,Launched,Intel UHD Graphics for 10th Generation Intel C...
3,Atom x6413E,2021.0,4,NaN,NaN,1.5,1.5,L2 Cache,NaN,NaN,Launched,Intel UHD Graphics for 10th Generation Intel C...
4,Atom x6414RE,2021.0,4,NaN,NaN,1.5,1.5,L2 Cache,NaN,NaN,Launched,Intel UHD Graphics for 10th Generation Intel C...

In [236]:
df2 = df2[df2['status'] == 'Launched']
df2 = df2[['product', 'releaseDate', 'cores', 'threads', 'baseClock', 'maxTurboClock', 'cache', 'cacheInfo']]
df2 = df2.rename(columns={'product': 'processor', 'releaseDate': 'year', 'maxTurboClock': 'maxboostClock'})

In [239]:
df2.tail()

,processor,year,cores,threads,baseClock,maxboostClock,cache,cacheInfo
1649,Pentium G2120,2012.0,2,NaN,3.1,NaN,3.0,Intel Smart Cache
1659,Xeon E3-1225 v2,2012.0,4,NaN,3.2,3.6,8.0,Intel Smart Cache
1665,Xeon E3-1275 v2,2012.0,4,NaN,3.5,3.9,8.0,Intel Smart Cache
1674,Xeon E5-2418L,2012.0,4,NaN,2.0,2.1,10.0,Intel Smart Cache
1680,Xeon E5-2448L,2012.0,8,NaN,1.8,2.1,20.0,Intel Smart Cache

In [189]:
#df3 = pd.concat([df, df2])